import "server-only";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * Private file storage on the server's disk (outside /public, never served directly).
 * Files are only reachable through the permission-checked route /api/fichiers/[id].
 * Can be swapped for MinIO / S3 later without changing callers.
 */
// Runtime-only path (env var): tell Turbopack not to trace it, or it would bundle the whole project.
const ROOT = path.resolve(/*turbopackIgnore: true*/ process.env.FILES_DIR ?? "./.data/files");

function resolveSafe(storagePath: string) {
  // storagePath is generated by us ("<uuid>.<ext>"); still refuse anything that escapes ROOT.
  const full = path.resolve(ROOT, storagePath);
  if (!full.startsWith(ROOT + path.sep)) throw new Error("Invalid storage path");
  return full;
}

export async function saveFile(storagePath: string, data: Buffer) {
  await mkdir(ROOT, { recursive: true });
  await writeFile(resolveSafe(storagePath), data, { flag: "wx" });
}

export async function readStoredFile(storagePath: string) {
  return readFile(resolveSafe(storagePath));
}

export async function deleteStoredFile(storagePath: string) {
  await unlink(resolveSafe(storagePath)).catch(() => undefined);
}

/** Check the real file content against its extension (don't trust the browser's MIME type). */
export function contentMatchesExtension(buf: Buffer, ext: string) {
  const startsWith = (...bytes: number[]) => bytes.every((b, i) => buf[i] === b);
  switch (ext) {
    case "pdf":
      return buf.subarray(0, 5).toString("latin1") === "%PDF-";
    case "png":
      return startsWith(0x89, 0x50, 0x4e, 0x47);
    case "jpg":
    case "jpeg":
      return startsWith(0xff, 0xd8, 0xff);
    case "webp":
      return buf.subarray(0, 4).toString("latin1") === "RIFF" && buf.subarray(8, 12).toString("latin1") === "WEBP";
    case "docx":
      return startsWith(0x50, 0x4b, 0x03, 0x04); // zip container
    case "doc":
      return startsWith(0xd0, 0xcf, 0x11, 0xe0);
    case "txt":
      return !buf.subarray(0, 4096).includes(0); // no binary content
    default:
      return false;
  }
}
